spring.datasource.url=jdbc:h2:mem:phones_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.port=9090
springdoc.packagesToScan=com.example.demo.controller